// 自動生成ファイル — 手で編集しないこと。
// 出典: 文部科学省「日本食品標準成分表（八訂）増補2023年」第2章（データ）本表
//       https://www.mext.go.jp/a_menu/syokuhinseibun/mext_00001.html
// 数値は可食部100gあたりの収載値をそのまま転記している（推測値・補完値は一切含まない）。
// id は成分表の食品番号。officialName は成分表の収載名で、出典の追跡用に保持している。
// estimated は成分表で括弧付き（推定値）だった項目名。
//
// 再生成の手順は docs/food-data.md を参照。

import type { Food } from './foods';

export const FOODS: readonly Food[] = [
  { id: '01088', name: 'ごはん（精白米）', emoji: '🍚', category: '穀類・主食', kcal: 156, protein: 2.5, fat: 0.3, carbs: 37.1, fiber: 1.5, salt: 0, officialName: 'こめ [水稲めし] 精白米 うるち米' },
  { id: '01085', name: 'ごはん（玄米）', emoji: '🍚', category: '穀類・主食', kcal: 152, protein: 2.8, fat: 1, carbs: 35.6, fiber: 1.4, salt: 0, officialName: 'こめ [水稲めし] 玄米' },
  { id: '01089', name: 'ごはん（胚芽精米）', emoji: '🍚', category: '穀類・主食', kcal: 159, protein: 2.7, fat: 0.6, carbs: 36.4, fiber: 0.8, salt: 0, officialName: 'こめ [水稲めし] はいが精米' },
  { id: '01155', name: 'ごはん（発芽玄米）', emoji: '🍚', category: '穀類・主食', kcal: 161, protein: 3, fat: 1.4, carbs: 35, fiber: 1.8, salt: 0, officialName: 'こめ [水稲めし] 発芽玄米' },
  { id: '01093', name: 'おかゆ（精白米・全がゆ）', emoji: '🍚', category: '穀類・主食', kcal: 65, protein: 1.1, fat: 0.1, carbs: 15.7, fiber: 0.1, salt: 0, officialName: 'こめ [水稲全かゆ] 精白米', estimated: ['protein', 'fat', 'carbs', 'fiber'] },
  { id: '01117', name: '切りもち', emoji: null, category: '穀類・主食', kcal: 223, protein: 4, fat: 0.6, carbs: 50.8, fiber: 0.5, salt: 0, officialName: 'こめ [もち米製品] もち' },
  { id: '01111', name: 'おにぎり', emoji: '🍙', category: '穀類・主食', kcal: 170, protein: 2.7, fat: 0.3, carbs: 39.4, fiber: 0.4, salt: 0.5, officialName: 'こめ [うるち米製品] おにぎり' },
  { id: '01118', name: '赤飯', emoji: '🍚', category: '穀類・主食', kcal: 186, protein: 4.3, fat: 0.6, carbs: 41.9, fiber: 1.6, salt: 0, officialName: 'こめ [もち米製品] 赤飯' },
  { id: '01026', name: '食パン（角形）', emoji: '🍞', category: '穀類・主食', kcal: 248, protein: 8.9, fat: 4.1, carbs: 46.4, fiber: 4.2, salt: 1.2, officialName: 'こむぎ [パン類] 角形食パン 食パン' },
  { id: '01205', name: '食パン（山形）', emoji: '🍞', category: '穀類・主食', kcal: 246, protein: 7.8, fat: 3.5, carbs: 47.9, fiber: 1.8, salt: 1.3, officialName: 'こむぎ [パン類] 山形食パン 食パン', estimated: ['protein', 'fat', 'carbs', 'fiber', 'salt'] },
  { id: '01032', name: 'ライ麦パン', emoji: '🍞', category: '穀類・主食', kcal: 252, protein: 8.4, fat: 2.2, carbs: 52.7, fiber: 5.6, salt: 1.2, officialName: 'こむぎ [パン類] ライ麦パン' },
  { id: '01034', name: 'ロールパン', emoji: '🍞', category: '穀類・主食', kcal: 309, protein: 10.1, fat: 9, carbs: 48.6, fiber: 2, salt: 1.2, officialName: 'こむぎ [パン類] ロールパン' },
  { id: '01035', name: 'クロワッサン', emoji: '🥐', category: '穀類・主食', kcal: 438, protein: 7.9, fat: 26.8, carbs: 43.9, fiber: 1.8, salt: 1.2, officialName: 'こむぎ [パン類] クロワッサン リッチタイプ' },
  { id: '01037', name: 'ナン', emoji: '🫓', category: '穀類・主食', kcal: 257, protein: 10.3, fat: 3.4, carbs: 47.6, fiber: 2, salt: 1.3, officialName: 'こむぎ [パン類] ナン' },
  { id: '01038', name: 'うどん（生）', emoji: '🍜', category: '穀類・主食', kcal: 249, protein: 6.1, fat: 0.6, carbs: 56.8, fiber: 3.6, salt: 2.5, officialName: 'こむぎ [うどん・そうめん類] うどん 生', estimated: ['fiber'] },
  { id: '01039', name: 'うどん（ゆで）', emoji: '🍜', category: '穀類・主食', kcal: 95, protein: 2.6, fat: 0.4, carbs: 21.6, fiber: 1.3, salt: 0.3, officialName: 'こむぎ [うどん・そうめん類] うどん ゆで', estimated: ['fiber'] },
  { id: '01043', name: 'そうめん・ひやむぎ（乾）', emoji: '🍜', category: '穀類・主食', kcal: 333, protein: 9.5, fat: 1.1, carbs: 72.7, fiber: 2.5, salt: 3.8, officialName: 'こむぎ [うどん・そうめん類] そうめん・ひやむぎ 乾' },
  { id: '01044', name: 'そうめん・ひやむぎ（ゆで）', emoji: '🍜', category: '穀類・主食', kcal: 114, protein: 3.5, fat: 0.4, carbs: 25.8, fiber: 0.9, salt: 0.2, officialName: 'こむぎ [うどん・そうめん類] そうめん・ひやむぎ ゆで' },
  { id: '01047', name: '中華めん（生）', emoji: '🍜', category: '穀類・主食', kcal: 249, protein: 8.6, fat: 1.2, carbs: 55.7, fiber: 5.4, salt: 1, officialName: 'こむぎ [中華めん類] 中華めん 生', estimated: ['fiber'] },
  { id: '01048', name: '中華めん（ゆで）', emoji: '🍜', category: '穀類・主食', kcal: 133, protein: 4.9, fat: 0.6, carbs: 29.2, fiber: 2.8, salt: 0.2, officialName: 'こむぎ [中華めん類] 中華めん ゆで', estimated: ['fiber'] },
  { id: '01049', name: '蒸し中華めん', emoji: '🍜', category: '穀類・主食', kcal: 162, protein: 4.9, fat: 1.7, carbs: 35.6, fiber: 3.1, salt: 0.3, officialName: 'こむぎ [中華めん類] 蒸し中華めん 蒸し中華めん' },
  { id: '01063', name: 'スパゲッティ（乾）', emoji: '🍝', category: '穀類・主食', kcal: 347, protein: 12.9, fat: 1.8, carbs: 73.1, fiber: 5.4, salt: 0, officialName: 'こむぎ [マカロニ・スパゲッティ類] マカロニ・スパゲッティ 乾' },
  { id: '01064', name: 'スパゲッティ（ゆで）', emoji: '🍝', category: '穀類・主食', kcal: 150, protein: 5.8, fat: 0.9, carbs: 32.2, fiber: 3, salt: 1.2, officialName: 'こむぎ [マカロニ・スパゲッティ類] マカロニ・スパゲッティ ゆで' },
  { id: '01127', name: 'そば（生）', emoji: '🍜', category: '穀類・主食', kcal: 271, protein: 9.8, fat: 1.9, carbs: 54.5, fiber: 6, salt: 0, officialName: 'そば そば 生', estimated: ['fiber'] },
  { id: '01128', name: 'そば（ゆで）', emoji: '🍜', category: '穀類・主食', kcal: 130, protein: 4.8, fat: 1, carbs: 26, fiber: 2.9, salt: 0, officialName: 'そば そば ゆで', estimated: ['fiber'] },
  { id: '01129', name: '干しそば（乾）', emoji: '🍜', category: '穀類・主食', kcal: 344, protein: 14, fat: 2.3, carbs: 66.7, fiber: 3.7, salt: 2.2, officialName: 'そば 干しそば 乾' },
  { id: '01004', name: 'オートミール', emoji: '🥣', category: '穀類・主食', kcal: 350, protein: 13.7, fat: 5.7, carbs: 69.1, fiber: 9.4, salt: 0, officialName: 'えんばく オートミール' },
  { id: '01137', name: 'コーンフレーク', emoji: '🥣', category: '穀類・主食', kcal: 380, protein: 7.8, fat: 1.7, carbs: 83.6, fiber: 2.4, salt: 2.1, officialName: 'とうもろこし コーンフレーク' },
  { id: '01020', name: '強力粉', emoji: null, category: '穀類・主食', kcal: 337, protein: 11.8, fat: 1.5, carbs: 71.7, fiber: 2.7, salt: 0, officialName: 'こむぎ [小麦粉] 強力粉 1等' },
  { id: '01015', name: '薄力粉', emoji: null, category: '穀類・主食', kcal: 349, protein: 8.3, fat: 1.5, carbs: 75.8, fiber: 2.5, salt: 0, officialName: 'こむぎ [小麦粉] 薄力粉 1等' },
  { id: '01079', name: 'パン粉（乾燥）', emoji: null, category: '穀類・主食', kcal: 349, protein: 14.9, fat: 4.1, carbs: 67.4, fiber: 6.5, salt: 1.4, officialName: 'こむぎ [その他] パン粉 乾燥' },
  { id: '01056', name: '即席中華めん（油揚げ・味付け）', emoji: '🍜', category: '穀類・主食', kcal: 424, protein: 10.1, fat: 16.7, carbs: 63.5, fiber: 2.5, salt: 6.4, officialName: 'こむぎ [即席めん類] 即席中華めん 油揚げ味付け' },
  { id: '02006', name: 'さつまいも（生）', emoji: '🍠', category: 'いも・でん粉', kcal: 126, protein: 1.2, fat: 0.2, carbs: 31.9, fiber: 2.2, salt: 0, officialName: '(さつまいも類) さつまいも 塊根 皮なし 生' },
  { id: '02008', name: 'さつまいも（焼き）', emoji: '🍠', category: 'いも・でん粉', kcal: 151, protein: 1.4, fat: 0.2, carbs: 39, fiber: 4.5, salt: 0, officialName: '(さつまいも類) さつまいも 塊根 皮なし 焼き' },
  { id: '02017', name: 'じゃがいも（生）', emoji: '🥔', category: 'いも・でん粉', kcal: 59, protein: 1.8, fat: 0.1, carbs: 17.3, fiber: 8.9, salt: 0, officialName: 'じゃがいも 塊茎 皮なし 生' },
  { id: '02018', name: 'じゃがいも（蒸し）', emoji: '🥔', category: 'いも・でん粉', kcal: 76, protein: 1.9, fat: 0.3, carbs: 18.1, fiber: 3.5, salt: 0, officialName: 'じゃがいも 塊茎 皮なし 蒸し' },
  { id: '02067', name: 'フライドポテト', emoji: '🍟', category: 'いも・でん粉', kcal: 159, protein: 2.7, fat: 5.9, carbs: 26.2, fiber: 3.9, salt: 0, officialName: 'じゃがいも 塊茎 皮なし フライドポテト (生を揚げたもの)' },
  { id: '02010', name: 'さといも（生）', emoji: null, category: 'いも・でん粉', kcal: 53, protein: 1.5, fat: 0.1, carbs: 13.1, fiber: 2.3, salt: 0, officialName: '(さといも類) さといも 球茎 生' },
  { id: '02023', name: 'ながいも（生）', emoji: null, category: 'いも・でん粉', kcal: 64, protein: 2.2, fat: 0.3, carbs: 13.9, fiber: 1, salt: 0, officialName: '(やまのいも類) ながいも ながいも 塊根 生' },
  { id: '02003', name: '板こんにゃく', emoji: null, category: 'いも・でん粉', kcal: 5, protein: 0.1, fat: 0, carbs: 2.3, fiber: 2.2, salt: 0, officialName: 'こんにゃく 板こんにゃく 精粉こんにゃく' },
  { id: '02005', name: 'しらたき', emoji: null, category: 'いも・でん粉', kcal: 7, protein: 0.2, fat: 0, carbs: 3, fiber: 2.9, salt: 0, officialName: 'こんにゃく しらたき' },
  { id: '03003', name: '上白糖', emoji: null, category: '砂糖・甘味', kcal: 391, protein: 0, fat: 0, carbs: 99.3, fiber: 0, salt: 0, officialName: '(砂糖類) 車糖 上白糖', estimated: ['protein', 'fat', 'fiber'] },
  { id: '03022', name: 'はちみつ', emoji: '🍯', category: '砂糖・甘味', kcal: 329, protein: 0.3, fat: 0, carbs: 81.9, fiber: 0, salt: 0, officialName: '(その他) はちみつ', estimated: ['fiber'] },
  { id: '03001', name: '黒砂糖', emoji: null, category: '砂糖・甘味', kcal: 352, protein: 1.7, fat: 0, carbs: 90.3, fiber: 0, salt: 0.1, officialName: '(砂糖類) 黒砂糖', estimated: ['fiber'] },
  { id: '04032', name: '木綿豆腐', emoji: null, category: '豆類', kcal: 73, protein: 7, fat: 4.9, carbs: 1.5, fiber: 1.1, salt: 0, officialName: 'だいず [豆腐・油揚げ類] 木綿豆腐' },
  { id: '04033', name: '絹ごし豆腐', emoji: null, category: '豆類', kcal: 56, protein: 5.3, fat: 3.5, carbs: 2, fiber: 0.9, salt: 0, officialName: 'だいず [豆腐・油揚げ類] 絹ごし豆腐' },
  { id: '04038', name: '焼き豆腐', emoji: null, category: '豆類', kcal: 82, protein: 7.8, fat: 5.7, carbs: 1, fiber: 0.5, salt: 0, officialName: 'だいず [豆腐・油揚げ類] 焼き豆腐' },
  { id: '04039', name: '厚揚げ（生揚げ）', emoji: null, category: '豆類', kcal: 143, protein: 10.7, fat: 11.3, carbs: 0.9, fiber: 0.8, salt: 0, officialName: 'だいず [豆腐・油揚げ類] 生揚げ' },
  { id: '04040', name: '油揚げ', emoji: null, category: '豆類', kcal: 377, protein: 23.4, fat: 34.4, carbs: 0.4, fiber: 1.3, salt: 0, officialName: 'だいず [豆腐・油揚げ類] 油揚げ 生' },
  { id: '04041', name: 'がんもどき', emoji: null, category: '豆類', kcal: 223, protein: 15.3, fat: 17.8, carbs: 1.6, fiber: 1.4, salt: 0.5, officialName: 'だいず [豆腐・油揚げ類] がんもどき' },
  { id: '04042', name: '高野豆腐（乾）', emoji: null, category: '豆類', kcal: 496, protein: 50.5, fat: 34.1, carbs: 4.2, fiber: 2.5, salt: 1.1, officialName: 'だいず [豆腐・油揚げ類] 凍り豆腐 乾' },
  { id: '04046', name: '納豆（糸引き）', emoji: '🫘', category: '豆類', kcal: 184, protein: 16.5, fat: 10, carbs: 12.1, fiber: 9.5, salt: 0, officialName: 'だいず [納豆類] 糸引き納豆' },
  { id: '04047', name: 'ひきわり納豆', emoji: '🫘', category: '豆類', kcal: 185, protein: 16.6, fat: 10, carbs: 10.5, fiber: 5.9, salt: 0, officialName: 'だいず [納豆類] 挽きわり納豆' },
  { id: '04051', name: 'おから（生）', emoji: null, category: '豆類', kcal: 88, protein: 6.1, fat: 3.6, carbs: 13.8, fiber: 11.5, salt: 0, officialName: 'だいず [その他] おから 生' },
  { id: '04052', name: '豆乳（無調整）', emoji: '🥛', category: '豆類', kcal: 43, protein: 3.6, fat: 2.8, carbs: 2.3, fiber: 0.9, salt: 0, officialName: 'だいず [その他] 豆乳 豆乳' },
  { id: '04053', name: '調製豆乳', emoji: '🥛', category: '豆類', kcal: 61, protein: 3.2, fat: 3.6, carbs: 4.8, fiber: 1.1, salt: 0.1, officialName: 'だいず [その他] 豆乳 調製豆乳' },
  { id: '04023', name: '大豆（国産・乾）', emoji: '🫘', category: '豆類', kcal: 372, protein: 33.8, fat: 19.7, carbs: 29.5, fiber: 21.5, salt: 0, officialName: 'だいず [全粒・全粒製品] 全粒 黄大豆 国産 乾' },
  { id: '04024', name: '大豆（国産・ゆで）', emoji: '🫘', category: '豆類', kcal: 163, protein: 14.8, fat: 9.8, carbs: 8.4, fiber: 8.5, salt: 0, officialName: 'だいず [全粒・全粒製品] 全粒 黄大豆 国産 ゆで' },
  { id: '04029', name: 'きな粉', emoji: null, category: '豆類', kcal: 451, protein: 36.7, fat: 25.7, carbs: 28.5, fiber: 18.1, salt: 0, officialName: 'だいず [全粒・全粒製品] きな粉 黄大豆 全粒大豆' },
  { id: '04078', name: 'いり大豆', emoji: '🫘', category: '豆類', kcal: 429, protein: 37.5, fat: 21.6, carbs: 33.3, fiber: 19.4, salt: 0, officialName: 'だいず [全粒・全粒製品] いり大豆 黄大豆' },
  { id: '04066', name: 'ひよこ豆（ゆで）', emoji: '🫘', category: '豆類', kcal: 149, protein: 9.5, fat: 2.5, carbs: 27.4, fiber: 11.6, salt: 0, officialName: 'ひよこまめ 全粒 ゆで' },
  { id: '04008', name: 'いんげん豆（ゆで）', emoji: '🫘', category: '豆類', kcal: 127, protein: 9.3, fat: 1.2, carbs: 24.5, fiber: 13.6, salt: 0, officialName: 'いんげんまめ 全粒 ゆで' },
  { id: '04002', name: 'あずき（ゆで）', emoji: '🫘', category: '豆類', kcal: 124, protein: 8.6, fat: 0.8, carbs: 25.6, fiber: 8.7, salt: 0, officialName: 'あずき 全粒 ゆで' },
  { id: '05001', name: 'アーモンド（乾）', emoji: '🥜', category: '種実類', kcal: 609, protein: 19.6, fat: 51.8, carbs: 20.9, fiber: 10.1, salt: 0, officialName: 'アーモンド 乾' },
  { id: '05040', name: 'アーモンド（無塩ロースト）', emoji: '🥜', category: '種実類', kcal: 608, protein: 20.3, fat: 54.1, carbs: 20.7, fiber: 11, salt: 0, officialName: 'アーモンド いり 無塩' },
  { id: '05014', name: 'くるみ（いり）', emoji: '🥜', category: '種実類', kcal: 713, protein: 14.6, fat: 68.8, carbs: 11.7, fiber: 7.5, salt: 0, officialName: 'くるみ いり' },
  { id: '05005', name: 'カシューナッツ（味付け）', emoji: '🥜', category: '種実類', kcal: 591, protein: 19.8, fat: 47.6, carbs: 26.7, fiber: 6.7, salt: 0.6, officialName: 'カシューナッツ フライ 味付け' },
  { id: '05034', name: 'ピーナッツ（乾）', emoji: '🥜', category: '種実類', kcal: 572, protein: 25.2, fat: 47, carbs: 19.4, fiber: 8.5, salt: 0, officialName: 'らっかせい 大粒種 乾' },
  { id: '05018', name: 'いりごま', emoji: null, category: '種実類', kcal: 605, protein: 20.3, fat: 54.2, carbs: 18.5, fiber: 12.6, salt: 0, officialName: 'ごま いり' },
  { id: '05026', name: 'ピスタチオ（味付け）', emoji: '🥜', category: '種実類', kcal: 617, protein: 17.4, fat: 56.1, carbs: 20.9, fiber: 9.2, salt: 0.7, officialName: 'ピスタチオ いり 味付け' },
  { id: '05006', name: 'かぼちゃの種（味付け）', emoji: '🥜', category: '種実類', kcal: 590, protein: 26.5, fat: 51.8, carbs: 12, fiber: 7.3, salt: 0.1, officialName: 'かぼちゃ いり 味付け' },
  { id: '06007', name: 'アスパラガス（生）', emoji: null, category: '野菜類', kcal: 21, protein: 2.6, fat: 0.2, carbs: 3.9, fiber: 1.8, salt: 0, officialName: 'アスパラガス 若茎 生' },
  { id: '06010', name: 'さやいんげん（生）', emoji: '🫛', category: '野菜類', kcal: 23, protein: 1.8, fat: 0.1, carbs: 5.1, fiber: 2.4, salt: 0, officialName: 'いんげんまめ さやいんげん 若ざや 生' },
  { id: '06032', name: 'オクラ（生）', emoji: null, category: '野菜類', kcal: 26, protein: 2.1, fat: 0.2, carbs: 6.6, fiber: 5, salt: 0, officialName: 'オクラ 果実 生' },
  { id: '06048', name: 'かぼちゃ（西洋・生）', emoji: '🎃', category: '野菜類', kcal: 78, protein: 1.9, fat: 0.3, carbs: 20.6, fiber: 3.5, salt: 0, officialName: '(かぼちゃ類) 西洋かぼちゃ 果実 生' },
  { id: '06061', name: 'キャベツ（生）', emoji: '🥬', category: '野菜類', kcal: 23, protein: 1.2, fat: 0.1, carbs: 5.2, fiber: 1.8, salt: 0, officialName: '(キャベツ類) キャベツ 結球葉 生' },
  { id: '06065', name: 'きゅうり（生）', emoji: '🥒', category: '野菜類', kcal: 13, protein: 1, fat: 0.1, carbs: 3, fiber: 1.1, salt: 0, officialName: 'きゅうり 果実 生' },
  { id: '06084', name: 'ごぼう（生）', emoji: null, category: '野菜類', kcal: 58, protein: 1.8, fat: 0.1, carbs: 15.4, fiber: 5.7, salt: 0, officialName: '(ごぼう類) ごぼう 根 生' },
  { id: '06086', name: '小松菜（生）', emoji: '🥬', category: '野菜類', kcal: 13, protein: 1.5, fat: 0.2, carbs: 2.4, fiber: 1.9, salt: 0, officialName: 'こまつな 葉 生' },
  { id: '06103', name: 'しょうが（生）', emoji: '🫚', category: '野菜類', kcal: 28, protein: 0.9, fat: 0.3, carbs: 6.6, fiber: 2.1, salt: 0, officialName: '(しょうが類) しょうが 根茎 皮なし 生' },
  { id: '06132', name: '大根（皮つき・生）', emoji: null, category: '野菜類', kcal: 15, protein: 0.5, fat: 0.1, carbs: 4.1, fiber: 1.4, salt: 0, officialName: '(だいこん類) だいこん 根 皮つき 生' },
  { id: '06134', name: '大根（皮なし・生）', emoji: null, category: '野菜類', kcal: 15, protein: 0.4, fat: 0.1, carbs: 4.1, fiber: 1.3, salt: 0, officialName: '(だいこん類) だいこん 根 皮なし 生' },
  { id: '06153', name: 'たまねぎ（生）', emoji: '🧅', category: '野菜類', kcal: 33, protein: 1, fat: 0.1, carbs: 8.4, fiber: 1.5, salt: 0, officialName: '(たまねぎ類) たまねぎ りん茎 生' },
  { id: '06336', name: 'たまねぎ（油いため）', emoji: '🧅', category: '野菜類', kcal: 100, protein: 1.4, fat: 5.9, carbs: 12, fiber: 2.7, salt: 0, officialName: '(たまねぎ類) たまねぎ りん茎 油いため' },
  { id: '06160', name: 'チンゲンサイ（生）', emoji: '🥬', category: '野菜類', kcal: 9, protein: 0.6, fat: 0.1, carbs: 2, fiber: 1.2, salt: 0.1, officialName: 'チンゲンサイ 葉 生' },
  { id: '06175', name: 'スイートコーン（生）', emoji: '🌽', category: '野菜類', kcal: 89, protein: 3.6, fat: 1.7, carbs: 16.8, fiber: 3, salt: 0, officialName: '(とうもろこし類) スイートコーン 未熟種子 生' },
  { id: '06180', name: 'スイートコーン（缶詰）', emoji: '🌽', category: '野菜類', kcal: 78, protein: 2.3, fat: 0.5, carbs: 17.8, fiber: 3.3, salt: 0.5, officialName: '(とうもろこし類) スイートコーン 缶詰 ホールカーネルスタイル' },
  { id: '06182', name: 'トマト（生）', emoji: '🍅', category: '野菜類', kcal: 20, protein: 0.7, fat: 0.1, carbs: 4.7, fiber: 1, salt: 0, officialName: '(トマト類) 赤色トマト 果実 生' },
  { id: '06183', name: 'ミニトマト（生）', emoji: '🍅', category: '野菜類', kcal: 30, protein: 1.1, fat: 0.1, carbs: 7.2, fiber: 1.4, salt: 0, officialName: '(トマト類) 赤色ミニトマト 果実 生' },
  { id: '06184', name: 'トマト缶（ホール・食塩無添加）', emoji: '🍅', category: '野菜類', kcal: 21, protein: 0.9, fat: 0.2, carbs: 4.4, fiber: 1.3, salt: 0, officialName: '(トマト類) 加工品 ホール 食塩無添加' },
  { id: '06191', name: 'なす（生）', emoji: '🍆', category: '野菜類', kcal: 18, protein: 1.1, fat: 0.1, carbs: 5.1, fiber: 2.2, salt: 0, officialName: '(なす類) なす 果実 生' },
  { id: '06207', name: 'にら（生）', emoji: null, category: '野菜類', kcal: 18, protein: 1.7, fat: 0.3, carbs: 4, fiber: 2.7, salt: 0, officialName: '(にら類) にら 葉 生' },
  { id: '06212', name: 'にんじん（皮つき・生）', emoji: '🥕', category: '野菜類', kcal: 35, protein: 0.7, fat: 0.2, carbs: 9.3, fiber: 2.8, salt: 0.1, officialName: '(にんじん類) にんじん 根 皮つき 生' },
  { id: '06214', name: 'にんじん（皮なし・生）', emoji: '🥕', category: '野菜類', kcal: 32, protein: 0.7, fat: 0.2, carbs: 8.8, fiber: 2.8, salt: 0.1, officialName: '(にんじん類) にんじん 根 皮なし 生' },
  { id: '06215', name: 'にんじん（皮なし・ゆで）', emoji: '🥕', category: '野菜類', kcal: 28, protein: 0.7, fat: 0.1, carbs: 8.5, fiber: 2.8, salt: 0.1, officialName: '(にんじん類) にんじん 根 皮なし ゆで' },
  { id: '06223', name: 'にんにく（生）', emoji: '🧄', category: '野菜類', kcal: 129, protein: 6.4, fat: 0.9, carbs: 27.5, fiber: 6.2, salt: 0, officialName: '(にんにく類) にんにく りん茎 生' },
  { id: '06226', name: '長ねぎ（生）', emoji: null, category: '野菜類', kcal: 35, protein: 1.4, fat: 0.1, carbs: 8.3, fiber: 2.5, salt: 0, officialName: '(ねぎ類) 根深ねぎ 葉 軟白 生' },
  { id: '06227', name: '葉ねぎ（生）', emoji: null, category: '野菜類', kcal: 29, protein: 1.9, fat: 0.3, carbs: 6.5, fiber: 3.2, salt: 0, officialName: '(ねぎ類) 葉ねぎ 葉 生' },
  { id: '06233', name: '白菜（生）', emoji: '🥬', category: '野菜類', kcal: 13, protein: 0.8, fat: 0.1, carbs: 3.2, fiber: 1.3, salt: 0, officialName: 'はくさい 結球葉 生' },
  { id: '06245', name: 'ピーマン（青・生）', emoji: '🫑', category: '野菜類', kcal: 20, protein: 0.9, fat: 0.2, carbs: 5.1, fiber: 2.3, salt: 0, officialName: '(ピーマン類) 青ピーマン 果実 生' },
  { id: '06247', name: 'パプリカ（赤・生）', emoji: '🫑', category: '野菜類', kcal: 28, protein: 1, fat: 0.2, carbs: 7.2, fiber: 1.6, salt: 0, officialName: '(ピーマン類) 赤ピーマン 果実 生' },
  { id: '06263', name: 'ブロッコリー（生）', emoji: '🥦', category: '野菜類', kcal: 37, protein: 5.4, fat: 0.6, carbs: 6.6, fiber: 5.1, salt: 0, officialName: 'ブロッコリー 花序 生' },
  { id: '06264', name: 'ブロッコリー（ゆで）', emoji: '🥦', category: '野菜類', kcal: 30, protein: 3.9, fat: 0.4, carbs: 5.2, fiber: 4.3, salt: 0, officialName: 'ブロッコリー 花序 ゆで' },
  { id: '06267', name: 'ほうれん草（生）', emoji: '🥬', category: '野菜類', kcal: 18, protein: 2.2, fat: 0.4, carbs: 3.1, fiber: 2.8, salt: 0, officialName: 'ほうれんそう 葉 通年平均 生' },
  { id: '06268', name: 'ほうれん草（ゆで）', emoji: '🥬', category: '野菜類', kcal: 23, protein: 2.6, fat: 0.5, carbs: 4, fiber: 3.6, salt: 0, officialName: 'ほうれんそう 葉 通年平均 ゆで' },
  { id: '06072', name: '水菜（生）', emoji: '🥬', category: '野菜類', kcal: 23, protein: 2.2, fat: 0.1, carbs: 4.8, fiber: 3, salt: 0.1, officialName: 'みずな 葉 生' },
  { id: '06287', name: '大豆もやし（生）', emoji: null, category: '野菜類', kcal: 29, protein: 3.6, fat: 1.4, carbs: 2.5, fiber: 2.3, salt: 0, officialName: '(もやし類) だいずもやし 生' },
  { id: '06291', name: 'もやし（緑豆・生）', emoji: null, category: '野菜類', kcal: 15, protein: 1.8, fat: 0.1, carbs: 2.4, fiber: 1.3, salt: 0, officialName: '(もやし類) りょくとうもやし 生' },
  { id: '06293', name: 'モロヘイヤ（生）', emoji: '🥬', category: '野菜類', kcal: 36, protein: 4.8, fat: 0.5, carbs: 6.3, fiber: 5.9, salt: 0, officialName: 'モロヘイヤ 茎葉 生' },
  { id: '06312', name: 'レタス（生）', emoji: '🥬', category: '野菜類', kcal: 11, protein: 0.6, fat: 0.1, carbs: 2.8, fiber: 1.1, salt: 0, officialName: '(レタス類) レタス 土耕栽培 結球葉 生' },
  { id: '06015', name: '枝豆（生）', emoji: '🫛', category: '野菜類', kcal: 125, protein: 11.7, fat: 6.2, carbs: 8.8, fiber: 5, salt: 0, officialName: 'えだまめ 生' },
  { id: '06016', name: '枝豆（ゆで）', emoji: '🫛', category: '野菜類', kcal: 118, protein: 11.5, fat: 6.1, carbs: 8.9, fiber: 4.6, salt: 0, officialName: 'えだまめ ゆで' },
  { id: '06054', name: 'カリフラワー（生）', emoji: null, category: '野菜類', kcal: 28, protein: 3, fat: 0.1, carbs: 5.2, fiber: 2.9, salt: 0, officialName: 'カリフラワー 花序 生' },
  { id: '06119', name: 'セロリ（生）', emoji: null, category: '野菜類', kcal: 12, protein: 0.4, fat: 0.1, carbs: 3.6, fiber: 1.5, salt: 0.1, officialName: 'セロリ 葉柄 生' },
  { id: '07107', name: 'バナナ', emoji: '🍌', category: '果実類', kcal: 93, protein: 1.1, fat: 0.2, carbs: 22.5, fiber: 1.1, salt: 0, officialName: 'バナナ 生' },
  { id: '07148', name: 'りんご（皮なし）', emoji: '🍎', category: '果実類', kcal: 53, protein: 0.1, fat: 0.2, carbs: 15.5, fiber: 1.4, salt: 0, officialName: 'りんご 皮なし 生' },
  { id: '07176', name: 'りんご（皮つき）', emoji: '🍎', category: '果実類', kcal: 56, protein: 0.2, fat: 0.3, carbs: 16.2, fiber: 1.9, salt: 0, officialName: 'りんご 皮つき 生' },
  { id: '07012', name: 'いちご', emoji: '🍓', category: '果実類', kcal: 31, protein: 0.9, fat: 0.1, carbs: 8.5, fiber: 1.4, salt: 0, officialName: 'いちご 生' },
  { id: '07027', name: 'みかん', emoji: '🍊', category: '果実類', kcal: 49, protein: 0.7, fat: 0.1, carbs: 12, fiber: 1, salt: 0, officialName: '(かんきつ類) うんしゅうみかん じょうのう 普通 生' },
  { id: '07040', name: 'オレンジ（ネーブル）', emoji: '🍊', category: '果実類', kcal: 48, protein: 0.9, fat: 0.1, carbs: 11.8, fiber: 1, salt: 0, officialName: '(かんきつ類) オレンジ ネーブル 砂じょう 生' },
  { id: '07062', name: 'グレープフルーツ（白肉種）', emoji: null, category: '果実類', kcal: 40, protein: 0.9, fat: 0.1, carbs: 9.6, fiber: 0.6, salt: 0, officialName: '(かんきつ類) グレープフルーツ 白肉種 砂じょう 生' },
  { id: '07054', name: 'キウイフルーツ（緑）', emoji: '🥝', category: '果実類', kcal: 51, protein: 1, fat: 0.2, carbs: 13.4, fiber: 2.6, salt: 0, officialName: 'キウイフルーツ 緑肉種 生' },
  { id: '07168', name: 'キウイフルーツ（黄）', emoji: '🥝', category: '果実類', kcal: 63, protein: 1.1, fat: 0.2, carbs: 14.9, fiber: 1.4, salt: 0, officialName: 'キウイフルーツ 黄肉種 生' },
  { id: '07116', name: 'ぶどう（皮なし）', emoji: '🍇', category: '果実類', kcal: 58, protein: 0.4, fat: 0.1, carbs: 15.7, fiber: 0.5, salt: 0, officialName: 'ぶどう 皮なし 生' },
  { id: '07124', name: 'ブルーベリー', emoji: '🫐', category: '果実類', kcal: 48, protein: 0.5, fat: 0.1, carbs: 12.9, fiber: 3.3, salt: 0, officialName: 'ブルーベリー 生' },
  { id: '07097', name: 'パイナップル', emoji: '🍍', category: '果実類', kcal: 54, protein: 0.6, fat: 0.1, carbs: 13.7, fiber: 1.2, salt: 0, officialName: 'パインアップル 生' },
  { id: '07136', name: 'もも（白肉種）', emoji: '🍑', category: '果実類', kcal: 38, protein: 0.6, fat: 0.1, carbs: 10.2, fiber: 1.3, salt: 0, officialName: '(もも類) もも 白肉種 生' },
  { id: '07088', name: '日本なし', emoji: '🍐', category: '果実類', kcal: 38, protein: 0.3, fat: 0.1, carbs: 11.3, fiber: 0.9, salt: 0, officialName: '(なし類) 日本なし 生' },
  { id: '07049', name: '柿（甘がき）', emoji: null, category: '果実類', kcal: 63, protein: 0.4, fat: 0.2, carbs: 15.9, fiber: 1.6, salt: 0, officialName: 'かき 甘がき 生' },
  { id: '07077', name: 'すいか', emoji: '🍉', category: '果実類', kcal: 41, protein: 0.6, fat: 0.1, carbs: 9.5, fiber: 0.3, salt: 0, officialName: 'すいか 赤肉種 生' },
  { id: '07134', name: 'メロン（温室）', emoji: '🍈', category: '果実類', kcal: 40, protein: 1.1, fat: 0.1, carbs: 10.3, fiber: 0.5, salt: 0, officialName: 'メロン 温室メロン 生' },
  { id: '07006', name: 'アボカド', emoji: '🥑', category: '果実類', kcal: 176, protein: 2.1, fat: 17.5, carbs: 7.9, fiber: 5.6, salt: 0, officialName: 'アボカド 生' },
  { id: '07155', name: 'レモン（全果）', emoji: '🍋', category: '果実類', kcal: 43, protein: 0.9, fat: 0.7, carbs: 12.5, fiber: 4.9, salt: 0, officialName: '(かんきつ類) レモン 全果 生' },
  { id: '08001', name: 'えのきたけ（生）', emoji: '🍄', category: 'きのこ類', kcal: 34, protein: 2.7, fat: 0.2, carbs: 7.6, fiber: 3.9, salt: 0, officialName: 'えのきたけ 生' },
  { id: '08039', name: 'しいたけ（生）', emoji: '🍄', category: 'きのこ類', kcal: 25, protein: 3.1, fat: 0.3, carbs: 6.4, fiber: 4.9, salt: 0, officialName: 'しいたけ 生しいたけ 菌床栽培 生' },
  { id: '08016', name: 'ぶなしめじ（生）', emoji: '🍄', category: 'きのこ類', kcal: 26, protein: 2.7, fat: 0.5, carbs: 4.8, fiber: 3, salt: 0, officialName: '(しめじ類) ぶなしめじ 生' },
  { id: '08028', name: 'まいたけ（生）', emoji: '🍄', category: 'きのこ類', kcal: 22, protein: 2, fat: 0.5, carbs: 4.4, fiber: 3.5, salt: 0, officialName: 'まいたけ 生' },
  { id: '08025', name: 'エリンギ（生）', emoji: '🍄', category: 'きのこ類', kcal: 31, protein: 2.8, fat: 0.4, carbs: 6, fiber: 3.4, salt: 0, officialName: '(ひらたけ類) エリンギ 生' },
  { id: '08020', name: 'なめこ（生）', emoji: '🍄', category: 'きのこ類', kcal: 21, protein: 1.8, fat: 0.2, carbs: 5.4, fiber: 3.4, salt: 0, officialName: 'なめこ 株採り 生' },
  { id: '08031', name: 'マッシュルーム（生）', emoji: '🍄', category: 'きのこ類', kcal: 15, protein: 2.9, fat: 0.3, carbs: 2.1, fiber: 2, salt: 0, officialName: 'マッシュルーム 生' },
  { id: '08007', name: 'きくらげ（ゆで）', emoji: '🍄', category: 'きのこ類', kcal: 14, protein: 0.6, fat: 0.2, carbs: 5.2, fiber: 5.2, salt: 0, officialName: '(きくらげ類) きくらげ ゆで' },
  { id: '09004', name: '焼きのり', emoji: null, category: '藻類', kcal: 297, protein: 41.4, fat: 3.7, carbs: 44.3, fiber: 36, salt: 1.3, officialName: 'あまのり 焼きのり' },
  { id: '09044', name: 'カットわかめ（乾）', emoji: null, category: '藻類', kcal: 186, protein: 17.9, fat: 4, carbs: 42.1, fiber: 39.2, salt: 23.5, officialName: 'わかめ カットわかめ 乾' },
  { id: '09039', name: 'わかめ（原藻・生）', emoji: null, category: '藻類', kcal: 24, protein: 1.9, fat: 0.2, carbs: 5.6, fiber: 3.6, salt: 1.5, officialName: 'わかめ 原藻 生' },
  { id: '09050', name: 'ひじき（乾）', emoji: null, category: '藻類', kcal: 180, protein: 9.2, fat: 3.2, carbs: 58.4, fiber: 51.8, salt: 4.7, officialName: 'ひじき ほしひじき ステンレス釜 乾' },
  { id: '09051', name: 'ひじき（ゆで）', emoji: null, category: '藻類', kcal: 11, protein: 0.7, fat: 0.3, carbs: 3.4, fiber: 3.7, salt: 0.1, officialName: 'ひじき ほしひじき ステンレス釜 ゆで' },
  { id: '09017', name: '真昆布（素干し）', emoji: null, category: '藻類', kcal: 170, protein: 5.8, fat: 1.3, carbs: 64.3, fiber: 32.1, salt: 6.6, officialName: '(こんぶ類) まこんぶ 素干し 乾' },
  { id: '09038', name: 'もずく（塩蔵・塩抜き）', emoji: null, category: '藻類', kcal: 4, protein: 0.2, fat: 0.1, carbs: 1.4, fiber: 1.4, salt: 0.2, officialName: '(もずく類) もずく 塩蔵 塩抜き' },
  { id: '10003', name: 'あじ（皮つき・生）', emoji: '🐟', category: '魚介類', kcal: 112, protein: 19.7, fat: 4.5, carbs: 0.1, fiber: 0, salt: 0.3, officialName: '(あじ類) まあじ 皮つき 生', estimated: ['fiber'] },
  { id: '10006', name: 'あじの開き（生）', emoji: '🐟', category: '魚介類', kcal: 150, protein: 20.2, fat: 8.8, carbs: 0.1, fiber: 0, salt: 1.7, officialName: '(あじ類) まあじ 開き干し 生', estimated: ['fiber'] },
  { id: '10047', name: 'いわし（生）', emoji: '🐟', category: '魚介類', kcal: 156, protein: 19.2, fat: 9.2, carbs: 0.2, fiber: 0, salt: 0.2, officialName: '(いわし類) まいわし 生', estimated: ['fiber'] },
  { id: '10055', name: 'しらす干し（微乾燥）', emoji: '🐟', category: '魚介類', kcal: 113, protein: 24.5, fat: 2.1, carbs: 0.1, fiber: 0, salt: 4.2, officialName: '(いわし類) しらす干し 微乾燥品' },
  { id: '10396', name: 'しらす（生）', emoji: '🐟', category: '魚介類', kcal: 67, protein: 15, fat: 1.3, carbs: 0.1, fiber: 0, salt: 1, officialName: '(いわし類) しらす 生', estimated: ['fiber'] },
  { id: '10060', name: 'いわし缶（水煮）', emoji: '🐟', category: '魚介類', kcal: 168, protein: 20.7, fat: 10.6, carbs: 0.1, fiber: 0, salt: 0.8, officialName: '(いわし類) 缶詰 水煮', estimated: ['fiber'] },
  { id: '10086', name: 'かつお（春獲り・生）', emoji: '🐟', category: '魚介類', kcal: 108, protein: 25.8, fat: 0.5, carbs: 0.1, fiber: 0, salt: 0.1, officialName: '(かつお類) かつお 春獲り 生', estimated: ['fiber'] },
  { id: '10087', name: 'かつお（秋獲り・生）', emoji: '🐟', category: '魚介類', kcal: 150, protein: 25, fat: 6.2, carbs: 0.2, fiber: 0, salt: 0.1, officialName: '(かつお類) かつお 秋獲り 生', estimated: ['fiber'] },
  { id: '10091', name: 'かつお節', emoji: '🐟', category: '魚介類', kcal: 332, protein: 77.1, fat: 2.9, carbs: 0.8, fiber: 0, salt: 0.3, officialName: '(かつお類) 加工品 かつお節', estimated: ['fiber'] },
  { id: '10134', name: 'さけ（しろさけ・生）', emoji: '🐟', category: '魚介類', kcal: 124, protein: 22.3, fat: 4.1, carbs: 0.1, fiber: 0, salt: 0.2, officialName: '(さけ・ます類) しろさけ 生', estimated: ['fiber'] },
  { id: '10136', name: 'さけ（しろさけ・焼き）', emoji: '🐟', category: '魚介類', kcal: 160, protein: 29.1, fat: 5.1, carbs: 0.1, fiber: 0, salt: 0.2, officialName: '(さけ・ます類) しろさけ 焼き', estimated: ['fiber'] },
  { id: '10139', name: '塩ざけ', emoji: '🐟', category: '魚介類', kcal: 183, protein: 22.4, fat: 11.1, carbs: 0.1, fiber: 0, salt: 1.8, officialName: '(さけ・ます類) しろさけ 塩ざけ', estimated: ['fiber'] },
  { id: '10144', name: 'サーモン（大西洋さけ・生）', emoji: '🐟', category: '魚介類', kcal: 218, protein: 20.1, fat: 16.5, carbs: 0.1, fiber: 0, salt: 0.1, officialName: '(さけ・ます類) たいせいようさけ 養殖 皮つき 生', estimated: ['fiber'] },
  { id: '10149', name: 'べにざけ（生）', emoji: '🐟', category: '魚介類', kcal: 127, protein: 22.5, fat: 4.5, carbs: 0.1, fiber: 0, salt: 0.1, officialName: '(さけ・ます類) べにざけ 生', estimated: ['fiber'] },
  { id: '10154', name: 'さば（生）', emoji: '🐟', category: '魚介類', kcal: 211, protein: 20.6, fat: 16.8, carbs: 0.3, fiber: 0, salt: 0.3, officialName: '(さば類) まさば 生', estimated: ['fiber'] },
  { id: '10156', name: 'さば（焼き）', emoji: '🐟', category: '魚介類', kcal: 264, protein: 25.2, fat: 22.4, carbs: 0.4, fiber: 0, salt: 0.3, officialName: '(さば類) まさば 焼き', estimated: ['fiber'] },
  { id: '10164', name: 'さば缶（水煮）', emoji: '🐟', category: '魚介類', kcal: 174, protein: 20.9, fat: 10.7, carbs: 0.2, fiber: 0, salt: 0.9, officialName: '(さば類) 缶詰 水煮', estimated: ['fiber'] },
  { id: '10171', name: 'さわら（生）', emoji: '🐟', category: '魚介類', kcal: 161, protein: 20.1, fat: 9.7, carbs: 0.1, fiber: 0, salt: 0.2, officialName: 'さわら 生', estimated: ['fiber'] },
  { id: '10173', name: 'さんま（皮つき・生）', emoji: '🐟', category: '魚介類', kcal: 287, protein: 18.1, fat: 25.6, carbs: 0.1, fiber: 0, salt: 0.4, officialName: 'さんま 皮つき 生', estimated: ['fiber'] },
  { id: '10180', name: 'ししゃも（生干し）', emoji: '🐟', category: '魚介類', kcal: 152, protein: 21, fat: 8.1, carbs: 0.2, fiber: 0, salt: 1.2, officialName: '(ししゃも類) ししゃも 生干し 生', estimated: ['fiber'] },
  { id: '10199', name: 'すけとうだら（生）', emoji: null, category: '魚介類', kcal: 72, protein: 17.4, fat: 1, carbs: 0.1, fiber: 0, salt: 0.3, officialName: '(たら類) すけとうだら 生', estimated: ['fiber'] },
  { id: '10202', name: 'たらこ（生）', emoji: '🐟', category: '魚介類', kcal: 131, protein: 24, fat: 4.7, carbs: 0.4, fiber: 0, salt: 4.6, officialName: '(たら類) すけとうだら たらこ 生', estimated: ['fiber'] },
  { id: '10205', name: 'まだら（生）', emoji: null, category: '魚介類', kcal: 72, protein: 17.6, fat: 0.2, carbs: 0.1, fiber: 0, salt: 0.3, officialName: '(たら類) まだら 生', estimated: ['fiber'] },
  { id: '10241', name: 'ぶり（生）', emoji: '🐟', category: '魚介類', kcal: 222, protein: 21.4, fat: 17.6, carbs: 0.3, fiber: 0, salt: 0.1, officialName: 'ぶり 成魚 生', estimated: ['fiber'] },
  { id: '10243', name: 'はまち（養殖・生）', emoji: '🐟', category: '魚介類', kcal: 217, protein: 20.7, fat: 17.2, carbs: 0.3, fiber: 0, salt: 0.1, officialName: 'ぶり はまち 養殖 皮つき 生', estimated: ['fiber'] },
  { id: '10246', name: 'ほっけ（生）', emoji: '🐟', category: '魚介類', kcal: 103, protein: 17.3, fat: 4.4, carbs: 0.1, fiber: 0, salt: 0.2, officialName: 'ほっけ 生', estimated: ['fiber'] },
  { id: '10252', name: 'まぐろ（きはだ・生）', emoji: '🐟', category: '魚介類', kcal: 102, protein: 24.3, fat: 1, carbs: 0, fiber: 0, salt: 0.1, officialName: '(まぐろ類) きはだ 生', estimated: ['fiber'] },
  { id: '10253', name: 'まぐろ（本まぐろ赤身・生）', emoji: '🐟', category: '魚介類', kcal: 115, protein: 26.4, fat: 1.4, carbs: 0.1, fiber: 0, salt: 0.1, officialName: '(まぐろ類) くろまぐろ 天然 赤身 生', estimated: ['fiber'] },
  { id: '10254', name: 'まぐろ（本まぐろ脂身・生）', emoji: '🐟', category: '魚介類', kcal: 308, protein: 20.1, fat: 27.5, carbs: 0.1, fiber: 0, salt: 0.2, officialName: '(まぐろ類) くろまぐろ 天然 脂身 生', estimated: ['fiber'] },
  { id: '10255', name: 'まぐろ（びんちょう・生）', emoji: '🐟', category: '魚介類', kcal: 111, protein: 26, fat: 0.7, carbs: 0.2, fiber: 0, salt: 0.1, officialName: '(まぐろ類) びんなが 生', estimated: ['fiber'] },
  { id: '10260', name: 'ツナ缶（水煮・ライト）', emoji: '🐟', category: '魚介類', kcal: 70, protein: 16, fat: 0.7, carbs: 0.2, fiber: 0, salt: 0.5, officialName: '(まぐろ類) 缶詰 水煮 フレーク ライト', estimated: ['fiber'] },
  { id: '10263', name: 'ツナ缶（油漬・ライト）', emoji: '🐟', category: '魚介類', kcal: 265, protein: 17.7, fat: 21.7, carbs: 0.1, fiber: 0, salt: 0.9, officialName: '(まぐろ類) 缶詰 油漬 フレーク ライト', estimated: ['fiber'] },
  { id: '10281', name: 'あさり（生）', emoji: null, category: '魚介類', kcal: 29, protein: 5.7, fat: 0.7, carbs: 0.4, fiber: 0, salt: 2, officialName: 'あさり 生', estimated: ['fiber'] },
  { id: '10292', name: 'かき（養殖・生）', emoji: '🦪', category: '魚介類', kcal: 58, protein: 6.9, fat: 2.2, carbs: 4.9, fiber: 0, salt: 1.2, officialName: 'かき 養殖 生', estimated: ['fiber'] },
  { id: '10311', name: 'ほたて（生）', emoji: null, category: '魚介類', kcal: 66, protein: 13.5, fat: 0.9, carbs: 1.5, fiber: 0, salt: 0.8, officialName: 'ほたてがい 生', estimated: ['fiber'] },
  { id: '10313', name: 'ほたて貝柱（生）', emoji: null, category: '魚介類', kcal: 82, protein: 16.9, fat: 0.3, carbs: 3.5, fiber: 0, salt: 0.3, officialName: 'ほたてがい 貝柱 生', estimated: ['fiber'] },
  { id: '10321', name: 'くるまえび（養殖・生）', emoji: '🦐', category: '魚介類', kcal: 90, protein: 21.6, fat: 0.6, carbs: 0, fiber: 0, salt: 0.4, officialName: '(えび類) くるまえび 養殖 生', estimated: ['fiber'] },
  { id: '10415', name: 'バナメイえび（養殖・生）', emoji: '🦐', category: '魚介類', kcal: 82, protein: 19.6, fat: 0.6, carbs: 0.7, fiber: 0, salt: 0.3, officialName: '(えび類) バナメイえび 養殖 生', estimated: ['fiber'] },
  { id: '10345', name: 'するめいか（生）', emoji: '🦑', category: '魚介類', kcal: 76, protein: 17.9, fat: 0.8, carbs: 0.1, fiber: 0, salt: 0.5, officialName: '(いか類) するめいか 生', estimated: ['fiber'] },
  { id: '10361', name: 'たこ（生）', emoji: '🐙', category: '魚介類', kcal: 70, protein: 16.1, fat: 0.9, carbs: 0.2, fiber: 0, salt: 1, officialName: '(たこ類) まだこ 皮つき 生', estimated: ['fiber'] },
  { id: '10376', name: 'かに風味かまぼこ', emoji: '🍥', category: '魚介類', kcal: 89, protein: 12.1, fat: 0.5, carbs: 9.2, fiber: 0, salt: 2.2, officialName: 'かに風味かまぼこ', estimated: ['fiber'] },
  { id: '10379', name: '蒸しかまぼこ', emoji: '🍥', category: '魚介類', kcal: 93, protein: 12, fat: 0.9, carbs: 9.7, fiber: 0, salt: 2.5, officialName: '蒸しかまぼこ', estimated: ['fiber'] },
  { id: '10381', name: 'ちくわ（焼き）', emoji: '🍥', category: '魚介類', kcal: 107, protein: 13.2, fat: 0.4, carbs: 13.3, fiber: 0, salt: 2.5, officialName: '焼き竹輪', estimated: ['fiber'] },
  { id: '10385', name: 'はんぺん', emoji: '🍥', category: '魚介類', kcal: 93, protein: 9.9, fat: 1, carbs: 11.4, fiber: 0, salt: 1.5, officialName: 'はんぺん', estimated: ['fiber'] },
  { id: '10386', name: 'さつま揚げ', emoji: '🍥', category: '魚介類', kcal: 116, protein: 11.3, fat: 2.4, carbs: 12.6, fiber: 0, salt: 2, officialName: 'さつま揚げ', estimated: ['fiber'] },
  { id: '10388', name: '魚肉ソーセージ', emoji: '🍥', category: '魚介類', kcal: 158, protein: 11.5, fat: 7.2, carbs: 12.6, fiber: 0, salt: 2.1, officialName: '魚肉ソーセージ', estimated: ['fiber'] },
  { id: '10067', name: 'うなぎ（養殖・生）', emoji: '🐟', category: '魚介類', kcal: 228, protein: 17.1, fat: 19.3, carbs: 0.3, fiber: 0, salt: 0.2, officialName: 'うなぎ 養殖 生', estimated: ['fiber'] },
  { id: '10070', name: 'うなぎのかば焼き', emoji: '🐟', category: '魚介類', kcal: 285, protein: 23, fat: 21, carbs: 3.1, fiber: 0, salt: 1.3, officialName: 'うなぎ かば焼', estimated: ['fiber'] },
  { id: '11030', name: '牛かた（乳用肥育・脂身つき）', emoji: '🥩', category: '肉類', kcal: 231, protein: 17.1, fat: 19.8, carbs: 0.3, fiber: 0, salt: 0.2, officialName: 'うし [乳用肥育牛肉] かた 脂身つき 生' },
  { id: '11032', name: '牛かた（乳用肥育・赤身）', emoji: '🥩', category: '肉類', kcal: 138, protein: 20.4, fat: 6.7, carbs: 0.2, fiber: 0, salt: 0.2, officialName: 'うし [乳用肥育牛肉] かた 赤肉 生' },
  { id: '11037', name: '牛リブロース（乳用肥育・脂身つき）', emoji: '🥩', category: '肉類', kcal: 380, protein: 14.1, fat: 37.1, carbs: 0.2, fiber: 0, salt: 0.1, officialName: 'うし [乳用肥育牛肉] リブロース 脂身つき 生', estimated: ['fiber'] },
  { id: '11043', name: '牛サーロイン（乳用肥育・脂身つき）', emoji: '🥩', category: '肉類', kcal: 313, protein: 16.5, fat: 27.9, carbs: 0.4, fiber: 0, salt: 0.1, officialName: 'うし [乳用肥育牛肉] サーロイン 脂身つき 生', estimated: ['fiber'] },
  { id: '11046', name: '牛ばら（乳用肥育・脂身つき）', emoji: '🥩', category: '肉類', kcal: 381, protein: 12.8, fat: 39.4, carbs: 0.3, fiber: 0, salt: 0.1, officialName: 'うし [乳用肥育牛肉] ばら 脂身つき 生', estimated: ['fiber'] },
  { id: '11047', name: '牛もも（乳用肥育・脂身つき）', emoji: '🥩', category: '肉類', kcal: 196, protein: 19.5, fat: 13.3, carbs: 0.4, fiber: 0, salt: 0.1, officialName: 'うし [乳用肥育牛肉] もも 脂身つき 生', estimated: ['fiber'] },
  { id: '11048', name: '牛もも（乳用肥育・皮下脂肪なし）', emoji: '🥩', category: '肉類', kcal: 169, protein: 20.5, fat: 9.9, carbs: 0.4, fiber: 0, salt: 0.1, officialName: 'うし [乳用肥育牛肉] もも 皮下脂肪なし 生', estimated: ['fiber'] },
  { id: '11051', name: '牛もも（乳用肥育・赤身）', emoji: '🥩', category: '肉類', kcal: 130, protein: 21.9, fat: 4.9, carbs: 0.4, fiber: 0, salt: 0.1, officialName: 'うし [乳用肥育牛肉] もも 赤肉 生', estimated: ['fiber'] },
  { id: '11059', name: '牛ヒレ（乳用肥育・赤身）', emoji: '🥩', category: '肉類', kcal: 177, protein: 20.8, fat: 11.2, carbs: 0.5, fiber: 0, salt: 0.1, officialName: 'うし [乳用肥育牛肉] ヒレ 赤肉 生', estimated: ['fiber'] },
  { id: '11071', name: '牛サーロイン（輸入・脂身つき）', emoji: '🥩', category: '肉類', kcal: 273, protein: 17.4, fat: 23.7, carbs: 0.4, fiber: 0, salt: 0.1, officialName: 'うし [輸入牛肉] サーロイン 脂身つき 生', estimated: ['fiber'] },
  { id: '11074', name: '牛ばら（輸入・脂身つき）', emoji: '🥩', category: '肉類', kcal: 338, protein: 14.4, fat: 32.9, carbs: 0.2, fiber: 0, salt: 0.1, officialName: 'うし [輸入牛肉] ばら 脂身つき 生', estimated: ['fiber'] },
  { id: '11075', name: '牛もも（輸入・脂身つき）', emoji: '🥩', category: '肉類', kcal: 148, protein: 19.6, fat: 8.6, carbs: 0.4, fiber: 0, salt: 0.1, officialName: 'うし [輸入牛肉] もも 脂身つき 生', estimated: ['fiber'] },
  { id: '11077', name: '牛もも（輸入・赤身）', emoji: '🥩', category: '肉類', kcal: 117, protein: 21.2, fat: 4.3, carbs: 0.4, fiber: 0, salt: 0.1, officialName: 'うし [輸入牛肉] もも 赤肉 生', estimated: ['fiber'] },
  { id: '11085', name: '牛ヒレ（輸入・赤身）', emoji: '🥩', category: '肉類', kcal: 123, protein: 20.5, fat: 4.8, carbs: 0.3, fiber: 0, salt: 0.1, officialName: 'うし [輸入牛肉] ヒレ 赤肉 生', estimated: ['fiber'] },
  { id: '11029', name: '牛ヒレ（和牛・赤身）', emoji: '🥩', category: '肉類', kcal: 207, protein: 19.1, fat: 15, carbs: 0.3, fiber: 0, salt: 0.1, officialName: 'うし [和牛肉] ヒレ 赤肉 生', estimated: ['fiber'] },
  { id: '11089', name: '牛ひき肉（生）', emoji: '🥩', category: '肉類', kcal: 251, protein: 17.1, fat: 21.1, carbs: 0.3, fiber: 0, salt: 0.2, officialName: 'うし [ひき肉] 生', estimated: ['fiber'] },
  { id: '11272', name: '牛ひき肉（焼き）', emoji: '🥩', category: '肉類', kcal: 280, protein: 25.9, fat: 21.3, carbs: 0.4, fiber: 0, salt: 0.2, officialName: 'うし [ひき肉] 焼き', estimated: ['fiber'] },
  { id: '11092', name: '牛レバー（生）', emoji: '🥩', category: '肉類', kcal: 119, protein: 19.6, fat: 3.7, carbs: 3.7, fiber: 0, salt: 0.1, officialName: 'うし [副生物] 肝臓 生', estimated: ['fiber'] },
  { id: '11104', name: 'ローストビーフ', emoji: '🥩', category: '肉類', kcal: 190, protein: 21.7, fat: 11.7, carbs: 0.9, fiber: 0, salt: 0.8, officialName: 'うし [加工品] ローストビーフ', estimated: ['fiber'] },
  { id: '11119', name: '豚かたロース（脂身つき）', emoji: '🥩', category: '肉類', kcal: 237, protein: 17.1, fat: 19.2, carbs: 0.1, fiber: 0, salt: 0.1, officialName: 'ぶた [大型種肉] かたロース 脂身つき 生', estimated: ['fiber'] },
  { id: '11123', name: '豚ロース（脂身つき・生）', emoji: '🥩', category: '肉類', kcal: 248, protein: 19.3, fat: 19.2, carbs: 0.2, fiber: 0, salt: 0.1, officialName: 'ぶた [大型種肉] ロース 脂身つき 生', estimated: ['fiber'] },
  { id: '11124', name: '豚ロース（脂身つき・焼き）', emoji: '🥩', category: '肉類', kcal: 310, protein: 26.7, fat: 22.7, carbs: 0.3, fiber: 0, salt: 0.1, officialName: 'ぶた [大型種肉] ロース 脂身つき 焼き', estimated: ['fiber'] },
  { id: '11126', name: '豚ロース（皮下脂肪なし）', emoji: '🥩', category: '肉類', kcal: 190, protein: 21.1, fat: 11.9, carbs: 0.3, fiber: 0, salt: 0.1, officialName: 'ぶた [大型種肉] ロース 皮下脂肪なし 生', estimated: ['fiber'] },
  { id: '11129', name: '豚ばら（脂身つき）', emoji: '🥩', category: '肉類', kcal: 366, protein: 14.4, fat: 35.4, carbs: 0.1, fiber: 0, salt: 0.1, officialName: 'ぶた [大型種肉] ばら 脂身つき 生', estimated: ['fiber'] },
  { id: '11130', name: '豚もも（脂身つき）', emoji: '🥩', category: '肉類', kcal: 171, protein: 20.5, fat: 10.2, carbs: 0.2, fiber: 0, salt: 0.1, officialName: 'ぶた [大型種肉] もも 脂身つき 生', estimated: ['fiber'] },
  { id: '11131', name: '豚もも（皮下脂肪なし）', emoji: '🥩', category: '肉類', kcal: 138, protein: 21.5, fat: 6, carbs: 0.2, fiber: 0, salt: 0.1, officialName: 'ぶた [大型種肉] もも 皮下脂肪なし 生', estimated: ['fiber'] },
  { id: '11140', name: '豚ヒレ（赤身・生）', emoji: '🥩', category: '肉類', kcal: 118, protein: 22.2, fat: 3.7, carbs: 0.3, fiber: 0, salt: 0.1, officialName: 'ぶた [大型種肉] ヒレ 赤肉 生', estimated: ['fiber'] },
  { id: '11278', name: '豚ヒレ（赤身・焼き）', emoji: '🥩', category: '肉類', kcal: 202, protein: 39.3, fat: 5.9, carbs: 0.4, fiber: 0, salt: 0.2, officialName: 'ぶた [大型種肉] ヒレ 赤肉 焼き', estimated: ['fiber'] },
  { id: '11163', name: '豚ひき肉（生）', emoji: '🥩', category: '肉類', kcal: 209, protein: 17.7, fat: 17.2, carbs: 0.1, fiber: 0, salt: 0.1, officialName: 'ぶた [ひき肉] 生', estimated: ['fiber'] },
  { id: '11166', name: '豚レバー（生）', emoji: '🥩', category: '肉類', kcal: 114, protein: 20.4, fat: 3.4, carbs: 2.5, fiber: 0, salt: 0.1, officialName: 'ぶた [副生物] 肝臓 生', estimated: ['fiber'] },
  { id: '11176', name: 'ロースハム', emoji: '🥩', category: '肉類', kcal: 211, protein: 18.6, fat: 14.5, carbs: 2, fiber: 0, salt: 2.3, officialName: 'ぶた [ハム類] ロースハム ロースハム', estimated: ['fiber'] },
  { id: '11183', name: 'ベーコン（ばら）', emoji: '🥓', category: '肉類', kcal: 241, protein: 15.4, fat: 19.4, carbs: 3.2, fiber: 0, salt: 2.6, officialName: 'ぶた [ベーコン類] ばらベーコン ばらベーコン', estimated: ['fiber'] },
  { id: '11186', name: 'ウインナーソーセージ', emoji: '🌭', category: '肉類', kcal: 319, protein: 11.5, fat: 30.6, carbs: 3.3, fiber: 0, salt: 1.9, officialName: 'ぶた [ソーセージ類] ウインナーソーセージ ウインナーソーセージ' },
  { id: '11181', name: '生ハム（促成）', emoji: '🥩', category: '肉類', kcal: 243, protein: 24, fat: 16.6, carbs: 0.5, fiber: 0, salt: 5.8, officialName: 'ぶた [ハム類] 生ハム 促成', estimated: ['fiber'] },
  { id: '11195', name: '焼き豚（チャーシュー）', emoji: '🥩', category: '肉類', kcal: 166, protein: 19.4, fat: 8.2, carbs: 5.1, fiber: 0, salt: 2.4, officialName: 'ぶた [その他] 焼き豚', estimated: ['fiber'] },
  { id: '11214', name: '鶏むね（親どり・皮なし）', emoji: '🍗', category: '肉類', kcal: 113, protein: 24.4, fat: 1.9, carbs: 0, fiber: 0, salt: 0.1, officialName: 'にわとり [親・主品目] むね 皮なし 生', estimated: ['fiber'] },
  { id: '11219', name: '鶏むね（若どり・皮つき・生）', emoji: '🍗', category: '肉類', kcal: 133, protein: 21.3, fat: 5.9, carbs: 0.1, fiber: 0, salt: 0.1, officialName: 'にわとり [若どり・主品目] むね 皮つき 生', estimated: ['fiber'] },
  { id: '11220', name: '鶏むね（若どり・皮なし・生）', emoji: '🍗', category: '肉類', kcal: 105, protein: 23.3, fat: 1.9, carbs: 0.1, fiber: 0, salt: 0.1, officialName: 'にわとり [若どり・主品目] むね 皮なし 生', estimated: ['fiber'] },
  { id: '11288', name: '鶏むね（若どり・皮なし・焼き）', emoji: '🍗', category: '肉類', kcal: 177, protein: 38.8, fat: 3.3, carbs: 0.1, fiber: 0, salt: 0.2, officialName: 'にわとり [若どり・主品目] むね 皮なし 焼き', estimated: ['fiber'] },
  { id: '11221', name: '鶏もも（若どり・皮つき・生）', emoji: '🍗', category: '肉類', kcal: 190, protein: 16.6, fat: 14.2, carbs: 0, fiber: 0, salt: 0.2, officialName: 'にわとり [若どり・主品目] もも 皮つき 生', estimated: ['fiber'] },
  { id: '11222', name: '鶏もも（若どり・皮つき・焼き）', emoji: '🍗', category: '肉類', kcal: 220, protein: 26.3, fat: 13.9, carbs: 0, fiber: 0, salt: 0.2, officialName: 'にわとり [若どり・主品目] もも 皮つき 焼き', estimated: ['fiber'] },
  { id: '11224', name: '鶏もも（若どり・皮なし・生）', emoji: '🍗', category: '肉類', kcal: 113, protein: 19, fat: 5, carbs: 0, fiber: 0, salt: 0.2, officialName: 'にわとり [若どり・主品目] もも 皮なし 生', estimated: ['fiber'] },
  { id: '11225', name: '鶏もも（若どり・皮なし・焼き）', emoji: '🍗', category: '肉類', kcal: 145, protein: 25.5, fat: 5.7, carbs: 0, fiber: 0, salt: 0.2, officialName: 'にわとり [若どり・主品目] もも 皮なし 焼き', estimated: ['fiber'] },
  { id: '11227', name: 'ささみ（生）', emoji: '🍗', category: '肉類', kcal: 98, protein: 23.9, fat: 0.8, carbs: 0.1, fiber: 0, salt: 0.1, officialName: 'にわとり [若どり・副品目] ささみ 生', estimated: ['fiber'] },
  { id: '11229', name: 'ささみ（ゆで）', emoji: '🍗', category: '肉類', kcal: 121, protein: 29.6, fat: 1, carbs: 0, fiber: 0, salt: 0.1, officialName: 'にわとり [若どり・副品目] ささみ ゆで', estimated: ['fiber'] },
  { id: '11228', name: 'ささみ（焼き）', emoji: '🍗', category: '肉類', kcal: 132, protein: 31.7, fat: 1.4, carbs: 0, fiber: 0, salt: 0.1, officialName: 'にわとり [若どり・副品目] ささみ 焼き', estimated: ['fiber'] },
  { id: '11218', name: '手羽（若どり・皮つき）', emoji: '🍗', category: '肉類', kcal: 189, protein: 17.8, fat: 14.3, carbs: 0, fiber: 0, salt: 0.2, officialName: 'にわとり [若どり・主品目] 手羽 皮つき 生', estimated: ['fiber'] },
  { id: '11230', name: '鶏ひき肉（生）', emoji: '🍗', category: '肉類', kcal: 171, protein: 17.5, fat: 12, carbs: 0, fiber: 0, salt: 0.1, officialName: 'にわとり [二次品目] ひき肉 生', estimated: ['fiber'] },
  { id: '11232', name: '鶏レバー（生）', emoji: '🍗', category: '肉類', kcal: 100, protein: 18.9, fat: 3.1, carbs: 0.6, fiber: 0, salt: 0.2, officialName: 'にわとり [副品目] 肝臓 生', estimated: ['fiber'] },
  { id: '11233', name: '砂肝（生）', emoji: '🍗', category: '肉類', kcal: 86, protein: 18.3, fat: 1.8, carbs: 0, fiber: 0, salt: 0.1, officialName: 'にわとり [副品目] すなぎも 生', estimated: ['fiber'] },
  { id: '11289', name: '鶏もも唐揚げ（皮つき）', emoji: '🍗', category: '肉類', kcal: 307, protein: 24.2, fat: 18.1, carbs: 13.3, fiber: 0.8, salt: 2.5, officialName: 'にわとり [若どり・主品目] もも 皮つき から揚げ' },
  { id: '11201', name: 'ラムかた（脂身つき）', emoji: '🥩', category: '肉類', kcal: 214, protein: 17.1, fat: 17.1, carbs: 0.1, fiber: 0, salt: 0.2, officialName: 'めんよう [ラム] かた 脂身つき 生', estimated: ['fiber'] },
  { id: '11202', name: 'ラムロース（脂身つき）', emoji: '🥩', category: '肉類', kcal: 287, protein: 15.6, fat: 25.9, carbs: 0.2, fiber: 0, salt: 0.2, officialName: 'めんよう [ラム] ロース 脂身つき 生', estimated: ['fiber'] },
  { id: '11203', name: 'ラムもも（脂身つき）', emoji: '🥩', category: '肉類', kcal: 164, protein: 20, fat: 12, carbs: 0.3, fiber: 0, salt: 0.2, officialName: 'めんよう [ラム] もも 脂身つき 生', estimated: ['fiber'] },
  { id: '11198', name: 'ゼラチン', emoji: null, category: '肉類', kcal: 347, protein: 87.6, fat: 0.3, carbs: 0, fiber: 0, salt: 0.7, officialName: 'ぶた [その他] ゼラチン', estimated: ['fiber'] },
  { id: '12004', name: '鶏卵（全卵・生）', emoji: '🥚', category: '卵類', kcal: 142, protein: 12.2, fat: 10.2, carbs: 0.4, fiber: 0, salt: 0.4, officialName: '鶏卵 全卵 生' },
  { id: '12005', name: 'ゆで卵', emoji: '🥚', category: '卵類', kcal: 134, protein: 12.5, fat: 10.4, carbs: 0.3, fiber: 0, salt: 0.3, officialName: '鶏卵 全卵 ゆで' },
  { id: '12021', name: '目玉焼き', emoji: '🍳', category: '卵類', kcal: 205, protein: 14.8, fat: 17.6, carbs: 0.3, fiber: 0, salt: 0.5, officialName: '鶏卵 全卵 目玉焼き' },
  { id: '12022', name: 'いり卵', emoji: '🍳', category: '卵類', kcal: 190, protein: 13.3, fat: 16.7, carbs: 0.3, fiber: 0, salt: 0.4, officialName: '鶏卵 全卵 いり' },
  { id: '12010', name: '卵黄（生）', emoji: '🥚', category: '卵類', kcal: 336, protein: 16.5, fat: 34.3, carbs: 0.2, fiber: 0, salt: 0.1, officialName: '鶏卵 卵黄 生' },
  { id: '12014', name: '卵白（生）', emoji: '🥚', category: '卵類', kcal: 44, protein: 10.1, fat: 0, carbs: 0.5, fiber: 0, salt: 0.5, officialName: '鶏卵 卵白 生' },
  { id: '12002', name: 'うずら卵（生）', emoji: '🥚', category: '卵類', kcal: 157, protein: 12.6, fat: 13.1, carbs: 0.3, fiber: 0, salt: 0.3, officialName: 'うずら卵 全卵 生', estimated: ['fiber'] },
  { id: '12018', name: '厚焼きたまご', emoji: '🍳', category: '卵類', kcal: 146, protein: 10.5, fat: 9.2, carbs: 6.5, fiber: 0, salt: 1.2, officialName: '鶏卵 たまご焼 厚焼きたまご', estimated: ['protein', 'fat', 'carbs', 'salt'] },
  { id: '13003', name: '牛乳（普通）', emoji: '🥛', category: '乳類', kcal: 61, protein: 3.3, fat: 3.8, carbs: 4.8, fiber: 0, salt: 0.1, officialName: '(液状乳類) 普通牛乳', estimated: ['fiber'] },
  { id: '13005', name: '加工乳（低脂肪）', emoji: '🥛', category: '乳類', kcal: 42, protein: 3.8, fat: 1, carbs: 5.5, fiber: 0, salt: 0.2, officialName: '(液状乳類) 加工乳 低脂肪', estimated: ['fiber'] },
  { id: '13006', name: '脱脂乳', emoji: '🥛', category: '乳類', kcal: 31, protein: 3.4, fat: 0.1, carbs: 4.8, fiber: 0, salt: 0.1, officialName: '(液状乳類) 脱脂乳', estimated: ['fiber'] },
  { id: '13010', name: 'スキムミルク', emoji: '🥛', category: '乳類', kcal: 354, protein: 34, fat: 1, carbs: 53.3, fiber: 0, salt: 1.4, officialName: '(粉乳類) 脱脂粉乳', estimated: ['fiber'] },
  { id: '13025', name: 'ヨーグルト（全脂無糖）', emoji: '🥛', category: '乳類', kcal: 56, protein: 3.6, fat: 3, carbs: 4.9, fiber: 0, salt: 0.1, officialName: '(発酵乳・乳酸菌飲料) ヨーグルト 全脂無糖', estimated: ['fiber'] },
  { id: '13053', name: 'ヨーグルト（低脂肪無糖）', emoji: '🥛', category: '乳類', kcal: 40, protein: 3.7, fat: 1, carbs: 5.2, fiber: 0, salt: 0.1, officialName: '(発酵乳・乳酸菌飲料) ヨーグルト 低脂肪無糖', estimated: ['fiber'] },
  { id: '13054', name: 'ヨーグルト（無脂肪無糖）', emoji: '🥛', category: '乳類', kcal: 37, protein: 4, fat: 0.3, carbs: 5.7, fiber: 0, salt: 0.1, officialName: '(発酵乳・乳酸菌飲料) ヨーグルト 無脂肪無糖', estimated: ['fiber'] },
  { id: '13026', name: 'ヨーグルト（脱脂加糖）', emoji: '🥛', category: '乳類', kcal: 65, protein: 4.3, fat: 0.2, carbs: 11.9, fiber: 0, salt: 0.2, officialName: '(発酵乳・乳酸菌飲料) ヨーグルト 脱脂加糖', estimated: ['fiber'] },
  { id: '13033', name: 'カテージチーズ', emoji: '🧀', category: '乳類', kcal: 99, protein: 13.3, fat: 4.5, carbs: 1.9, fiber: 0, salt: 1, officialName: '(チーズ類) ナチュラルチーズ カテージ', estimated: ['fiber'] },
  { id: '13034', name: 'カマンベールチーズ', emoji: '🧀', category: '乳類', kcal: 291, protein: 19.1, fat: 24.7, carbs: 0.9, fiber: 0, salt: 2, officialName: '(チーズ類) ナチュラルチーズ カマンベール', estimated: ['fiber'] },
  { id: '13035', name: 'クリームチーズ', emoji: '🧀', category: '乳類', kcal: 313, protein: 8.2, fat: 33, carbs: 2.3, fiber: 0, salt: 0.7, officialName: '(チーズ類) ナチュラルチーズ クリーム', estimated: ['fiber'] },
  { id: '13037', name: 'チェダーチーズ', emoji: '🧀', category: '乳類', kcal: 390, protein: 25.7, fat: 33.8, carbs: 1.4, fiber: 0, salt: 2, officialName: '(チーズ類) ナチュラルチーズ チェダー', estimated: ['fiber'] },
  { id: '13038', name: 'パルメザンチーズ', emoji: '🧀', category: '乳類', kcal: 445, protein: 44, fat: 30.8, carbs: 1.9, fiber: 0, salt: 3.8, officialName: '(チーズ類) ナチュラルチーズ パルメザン', estimated: ['fiber'] },
  { id: '13056', name: 'モッツァレラチーズ', emoji: '🧀', category: '乳類', kcal: 269, protein: 18.4, fat: 19.9, carbs: 4.2, fiber: 0, salt: 0.2, officialName: '(チーズ類) ナチュラルチーズ モッツァレラ', estimated: ['fiber'] },
  { id: '13040', name: 'プロセスチーズ', emoji: '🧀', category: '乳類', kcal: 313, protein: 22.7, fat: 26, carbs: 1.3, fiber: 0, salt: 2.8, officialName: '(チーズ類) プロセスチーズ', estimated: ['fiber'] },
  { id: '13043', name: 'アイスクリーム（普通脂肪）', emoji: '🍦', category: '乳類', kcal: 178, protein: 3.9, fat: 8, carbs: 23.2, fiber: 0.1, salt: 0.3, officialName: '(アイスクリーム類) アイスクリーム 普通脂肪' },
  { id: '13014', name: '生クリーム（乳脂肪）', emoji: '🥛', category: '乳類', kcal: 404, protein: 1.9, fat: 43, carbs: 6.5, fiber: 0, salt: 0.1, officialName: '(クリーム類) クリーム 乳脂肪' },
  { id: '14001', name: 'オリーブ油', emoji: '🫒', category: '油脂類', kcal: 894, protein: 0, fat: 100, carbs: 0, fiber: 0, salt: 0, officialName: '(植物油脂類) オリーブ油' },
  { id: '14002', name: 'ごま油', emoji: null, category: '油脂類', kcal: 890, protein: 0, fat: 100, carbs: 0, fiber: 0, salt: 0, officialName: '(植物油脂類) ごま油' },
  { id: '14008', name: 'なたね油', emoji: null, category: '油脂類', kcal: 887, protein: 0, fat: 100, carbs: 0, fiber: 0, salt: 0, officialName: '(植物油脂類) なたね油' },
  { id: '14006', name: 'サラダ油（調合油）', emoji: null, category: '油脂類', kcal: 886, protein: 0, fat: 100, carbs: 0, fiber: 0, salt: 0, officialName: '(植物油脂類) 調合油' },
  { id: '14017', name: 'バター（有塩）', emoji: '🧈', category: '油脂類', kcal: 700, protein: 0.6, fat: 81, carbs: 0.2, fiber: 0, salt: 1.9, officialName: '(バター類) 無発酵バター 有塩バター', estimated: ['fiber'] },
  { id: '14020', name: 'マーガリン（有塩）', emoji: '🧈', category: '油脂類', kcal: 715, protein: 0.4, fat: 83.1, carbs: 0.5, fiber: 0, salt: 1.3, officialName: '(マーガリン類) マーガリン 家庭用 有塩', estimated: ['fiber'] },
  { id: '14016', name: 'ラード', emoji: null, category: '油脂類', kcal: 885, protein: 0, fat: 100, carbs: 0, fiber: 0, salt: 0, officialName: '(動物油脂類) ラード' },
  { id: '16006', name: 'ビール（淡色）', emoji: '🍺', category: 'し好飲料', kcal: 39, protein: 0.3, fat: 0, carbs: 3.1, fiber: 0, salt: 0, officialName: '(醸造酒類) ビール 淡色' },
  { id: '16001', name: '清酒（普通酒）', emoji: '🍶', category: 'し好飲料', kcal: 107, protein: 0.4, fat: 0, carbs: 4.9, fiber: 0, salt: 0, officialName: '(醸造酒類) 清酒 普通酒' },
  { id: '16037', name: '緑茶（せん茶・浸出液）', emoji: '🍵', category: 'し好飲料', kcal: 2, protein: 0.2, fat: 0, carbs: 0.2, fiber: null, salt: 0, officialName: '(緑茶類) せん茶 浸出液', estimated: ['fat'] },
  { id: '16045', name: 'コーヒー（浸出液）', emoji: '☕', category: 'し好飲料', kcal: 4, protein: 0.2, fat: 0, carbs: 0.7, fiber: null, salt: 0, officialName: 'コーヒー 浸出液' },
  { id: '17007', name: 'しょうゆ（濃口）', emoji: null, category: '調味料', kcal: 76, protein: 7.7, fat: 0, carbs: 7.9, fiber: 0, salt: 14.5, officialName: '(しょうゆ類) こいくちしょうゆ', estimated: ['fiber'] },
  { id: '17008', name: 'しょうゆ（薄口）', emoji: null, category: '調味料', kcal: 60, protein: 5.7, fat: 0, carbs: 5.8, fiber: 0, salt: 16, officialName: '(しょうゆ類) うすくちしょうゆ', estimated: ['fiber'] },
  { id: '17045', name: 'みそ（淡色辛みそ）', emoji: null, category: '調味料', kcal: 182, protein: 12.5, fat: 6, carbs: 21.9, fiber: 4.9, salt: 12.4, officialName: '(みそ類) 米みそ 淡色辛みそ' },
  { id: '17046', name: 'みそ（赤色辛みそ）', emoji: null, category: '調味料', kcal: 178, protein: 13.1, fat: 5.5, carbs: 21.1, fiber: 4.1, salt: 13, officialName: '(みそ類) 米みそ 赤色辛みそ' },
  { id: '17036', name: 'トマトケチャップ', emoji: '🍅', category: '調味料', kcal: 116, protein: 1.6, fat: 0.2, carbs: 27.6, fiber: 1.7, salt: 3.1, officialName: '(トマト加工品類) トマトケチャップ' },
  { id: '17042', name: 'マヨネーズ（全卵型）', emoji: null, category: '調味料', kcal: 668, protein: 1.4, fat: 76, carbs: 3.6, fiber: 0, salt: 1.9, officialName: '(ドレッシング類) 半固体状ドレッシング マヨネーズ 全卵型', estimated: ['fiber'] },
  { id: '17001', name: 'ウスターソース', emoji: null, category: '調味料', kcal: 117, protein: 1, fat: 0.1, carbs: 27.1, fiber: 0.5, salt: 8.5, officialName: '(ウスターソース類) ウスターソース' },
  { id: '17002', name: '中濃ソース', emoji: null, category: '調味料', kcal: 129, protein: 0.8, fat: 0.1, carbs: 30.9, fiber: 1, salt: 5.8, officialName: '(ウスターソース類) 中濃ソース' },
  { id: '17015', name: '穀物酢', emoji: null, category: '調味料', kcal: 25, protein: 0.1, fat: 0, carbs: 2.4, fiber: 0, salt: 0, officialName: '(食酢類) 穀物酢', estimated: ['fiber'] },
  { id: '17012', name: '食塩', emoji: '🧂', category: '調味料', kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, salt: 99.5, officialName: '(食塩類) 食塩', estimated: ['fiber'] },
  { id: '17031', name: 'オイスターソース', emoji: null, category: '調味料', kcal: 105, protein: 7.7, fat: 0.3, carbs: 18.3, fiber: 0.2, salt: 11.4, officialName: '(調味ソース類) オイスターソース' },
  { id: '17029', name: 'めんつゆ（ストレート）', emoji: null, category: '調味料', kcal: 44, protein: 2.2, fat: 0, carbs: 8.7, fiber: null, salt: 3.3, officialName: '(だし類) めんつゆ ストレート' },
  { id: '17051', name: 'カレールウ', emoji: '🍛', category: '調味料', kcal: 474, protein: 6.5, fat: 34.1, carbs: 44.7, fiber: 6.4, salt: 10.6, officialName: '(ルウ類) カレールウ' },
];
